### ISSUE TITLE
Show Win+Alt+V doesn't work for your own post.

### ISSUE THREAD

**Issue by chigkim** [manuelcortez/TWBlue#649]
I can view detail for posts that other people posted with win+alt+v.
However, it doesn't do anything if I press win+alt+v for my own post.
I just updated to 2024.05.23, and I'm sure it used to work.

**Comment by jeremyp3** [comment]
fixed in #637 

1. stop TWBlue
2. unzip file
3. copy and replace file message.pyc in *twblue*/lib/controller/mastodon directory 
4. star TWBlue

[messages.pyc.zip.zip](https://github.com/MCV-Software/TWBlue/files/15446908/messages.pyc.zip.zip)

**Comment by chigkim** [comment]
Isn't the UnicodeEncodeError supposed to be fixed in 2024.05.23 though? Or, is this a different bug?

**Comment by manuelcortez** [comment]
Hi, it was a different bug but it should be fixed already after last release. Closing.

**Comment by chigkim** [comment]
I upgraded to Version 2024.05.23, and I still can't see my own post with alt+win+v.

My name doesn't have any weird characters, but my bio has emojis.

**Comment by manuelcortez** [comment]
Yes, that's why i mentioned last release. I mean it has been fixed in source code and should be available for everybody on next release.

**Comment by chigkim** [comment]
Ah ok. I'll wait for the next release! Thanks.

**Comment by chigkim** [comment]
Is there a snapshot build I can try?
If not, any estimate for next release date?
I could run main.py and use it, but when I build it, I get this:
```bash
Missing dependencies:
? api-ms-win-core-path-l1-1-0.dll
? api-ms-win-core-winrt-error-l1-1-0.dll
? api-ms-win-core-winrt-l1-1-0.dll
? api-ms-win-core-winrt-string-l1-1-0.dll
? libffi-6.dll
This is not necessarily a problem - the dependencies may not be needed on this platform.
```
If I run twblue.exe in distit folder, it just exits with no error. However, I can see from the task manager that it's running in the background.
There's no GUI, and shortcuts don't work.
Thanks for your help!
